import type { Metadata } from "next";

import localFont from "next/font/local";

import "./globals.css";

const inter = localFont({
  src: [
    {
      path: "../../../../public/fonts/Inter-VariableFont_slnt,wght.ttf",
    },
  ],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body className={`${inter.variable} font-inter relative`}>
        {children}
      </body>
    </html>
  );
}
